cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    path('',
         views.cart_detail,
         name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('checkout/', include('checkout.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('products/',
         views.ProductListView.as_view(),
         name='product_list'),
    path('products/<slug:category_slug>/',
         views.ProductListView.as_view(),
         name='product_list_by_category'),
    path('products/<int:pk>/<slug:slug>/',
         views.ProductDetailView.as_view(),
         name='product_detail'),
    path('',
         views.IndexView.as_view(),
         name='home')
]

shop/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator, \
    MaxValueValidator
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            verbose_name='Категория')
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=30,
                            verbose_name='Тег')

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE,
                                 verbose_name='Категория')
    name = models.CharField(max_length=200,
                            verbose_name='Название')
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True,
                              verbose_name='Изображение')
    description = models.TextField(blank=True,
                                   verbose_name='Описание')
    price = models.DecimalField(max_digits=10,
                                decimal_places=2,
                                verbose_name='Цена')
    discount = models.IntegerField(
        validators=[MinValueValidator(0),
                    MaxValueValidator(100)],
        default=0,
        verbose_name='Скидка',
        help_text='Значение в процентах (от 0 до 100)'
    )
    tags = models.ManyToManyField(Tag, blank=True,
                                  verbose_name='Теги')
    available = models.BooleanField(default=True,
                                    verbose_name='В продаже')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата добавления')
    updated = models.DateTimeField(auto_now=True,
                                   verbose_name='Дата последнего обновления')

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    def get_discount(self):
        if self.discount:
            return self.discount / Decimal(100) \
                * self.price
        return 0

    def get_price_after_discount(self):
        return Decimal('{:.2f}'.format(self.price - self.get_discount()))

    def __str__(self):
        return self.name


class AdditionalProductImage(models.Model):
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              verbose_name='Изображение')
    product = models.ForeignKey(Product,
                                related_name='additional_images',
                                on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'


class Review(models.Model):
    pass

shop/views.py
from django.core.paginator import Paginator, \
    EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, \
    ListView, DetailView
from django.shortcuts import get_object_or_404

from . import models
from cart.cart import Cart


class IndexView(TemplateView):
    template_name = 'shop/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        context['categories'] = models.Category.objects.all()
        context['latest_products'] = models.Product.objects.all()[:6]
        context['top_sellers'] = models.Product.objects.all()[:3]
        context['recently_viewed'] = models.Product.objects.all()[:3]
        context['top_new'] = models.Product.objects.all()[:3]
        return context


class ProductListView(ListView):
    template_name = 'shop/product/list.html'
    model = models.Product
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        context['categories'] = models.Category.objects.all()

        product_list = models.Product.objects.filter(available=True)

        category_slug = self.kwargs.get('category_slug')
        if category_slug:
            category = get_object_or_404(models.Category, slug=category_slug)
            context['object_list'] = product_list.filter(category=category)

        paginator = Paginator(product_list, self.paginate_by)
        page_number = self.request.GET.get('page', 1)
        try:
            products = paginator.page(page_number)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context['object_list'] = products
        return context


class ProductDetailView(DetailView):
    template_name = 'shop/product/detail.html'
    model = models.Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        context['categories'] = models.Category.objects.all()
        context['other_products'] = models.Product.objects.exclude(id=self.object.id)[:4]
        return context

shop/templates/shop/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SHOP{% endblock %}
{% block main %}

    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">

                {% include 'includes/sidebar.html' %}

                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="product-breadcroumb">
                            <a href="{% url 'shop:home' %}">Home</a>
                            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
                            <a href="{{ product.get_absolute_url }}">{{ product }}</a>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="product-images">
                                    <div class="product-main-img">
                                        {% if object.image %}
                                            <img src="{{ object.image.url }}" alt="">
                                        {% else %}
                                            <img src="{% static 'img/no_image.png' %}" alt="">
                                        {% endif %}
                                    </div>

                                    <div class="product-gallery">
                                        {% for image in object.additional_images.all %}
                                            <img src="{{ image.url }}" alt="">
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="product-inner">
                                    <h2 class="product-name">{{ object }}</h2>
                                    <div class="product-inner-price">
                                        {% if object.discount %}
                                            <ins>${{ object.get_price_after_discount }}</ins>
                                            <del>${{ object.price }}</del>
                                        {% else %}
                                            <ins>${{ object.price }}</ins>
                                        {% endif %}
                                    </div>

                                    <form action="{% url 'cart:cart_add' object.id %}" class="cart" method="post">
                                        {% csrf_token %}
                                        <div class="quantity">
                                            <input type="number" size="4" class="input-text qty text" title="Qty"
                                                   value="1" name="quantity" min="1" step="1">
                                        </div>
                                        <button class="add_to_cart_button" type="submit">Add to cart</button>
                                    </form>

                                    <div class="product-inner-category">
                                        <p>Category: <a
                                                href="{{ object.category.get_absolute_url }}">{{ object.category }}</a>.
                                            Tags:
                                            {% for tag in object.tags.all %}
                                                {% if forloop.last %}
                                                    {{ tag }}.
                                                {% else %}
                                                    {{ tag }},
                                                {% endif %}
                                            {% endfor %}
                                    </div>

                                    <div role="tabpanel">
                                        <ul class="product-tab" role="tablist">
                                            <li role="presentation" class="active"><a href="#home" aria-controls="home"
                                                                                      role="tab" data-toggle="tab">Description</a>
                                            </li>
                                            <li role="presentation"><a href="#profile" aria-controls="profile"
                                                                       role="tab" data-toggle="tab">Reviews</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade in active" id="home">
                                                <h2>Product Description</h2>
                                                <p>{{ object.description }}</p>
                                            </div>
                                            <div role="tabpanel" class="tab-pane fade" id="profile">
                                                <h2>Reviews</h2>
                                                <div class="submit-review">
                                                    <p><label for="name">Name</label> <input name="name" type="text">
                                                    </p>
                                                    <p><label for="email">Email</label> <input name="email"
                                                                                               type="email"></p>
                                                    <div class="rating-chooser">
                                                        <p>Your rating</p>

                                                        <div class="rating-wrap-post">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <p><label for="review">Your review</label> <textarea name="review"
                                                                                                         id="" cols="30"
                                                                                                         rows="10"></textarea>
                                                    </p>
                                                    <p><input type="submit" value="Submit"></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>


                        <div class="related-products-wrapper">
                            <h2 class="related-products-title">Related Products</h2>
                            <div class="related-products-carousel">
                                {% for product in other_products %}
                                    <div class="single-product">
                                        <div class="product-f-image">
                                            {% if product.image %}
                                                <img src="{{ product.image.url }}" style="height: 300px" alt="">
                                            {% else %}
                                                <img src="{% static 'img/no_image.png' %}" style="height: 300px" alt="">
                                            {% endif %}
                                            <div class="product-hover">
                                                <a href="" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i>
                                                    Add to cart</a>
                                                <a href="{{ product.get_absolute_url }}" class="view-details-link"><i
                                                        class="fa fa-link"></i> See
                                                    details</a>
                                            </div>
                                        </div>

                                        <h2><a href="{{ product.get_absolute_url }}">{{ product }}</a></h2>

                                        <div class="product-carousel-price">
                                            {% if product.discount %}
                                                <ins>${{ product.get_price_after_discount }}</ins>
                                                <del>${{ product.price }}</del>
                                            {% else %}
                                                <ins>${{ product.price }}</ins>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SHOP{% endblock %}
{% block main %}

    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                {% for obj in object_list %}
                    <div class="col-md-3 col-sm-6">
                        <div class="single-shop-product">
                            <div class="product-upper">
                                {% if obj.image %}
                                    <img src="{{ obj.image.url }}" style="height: 180px" alt="">
                                {% else %}
                                    <img src="{% static 'img/no_image.png' %}" style="height: 180px" alt="no image">
                                {% endif %}
                            </div>
                            <h2><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></h2>
                            <div class="product-carousel-price">
                                {% if obj.discount %}
                                    <ins>${{ obj.get_price_after_discount }}</ins>
                                    <del>${{ obj.price }}</del>
                                {% else %}
                                    <ins>${{ obj.price }}</ins>
                                {% endif %}
                            </div>

                            <div class="product-option-shop">
                                <form action="{% url 'cart:cart_add' obj.id %}" class="cart" method="post">
                                        {% csrf_token %}
                                        <button class="add_to_cart_button" type="submit" value="1" name="quantity">Add to cart</button>
                                    </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% include 'includes/pagination.html' %}

        </div>
    </div>
{% endblock %}